# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # TODO: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: '1ff828bd-337c-4918-ae04-6eb0ac320825'
#test
  # TODO: Specify the value of the existing Web App name
  webAppName: 'flask-appservice2024032301'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'flask-appservice2024032301'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.8'

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy stage
  jobs:
  - job: BuildAndDeployJob
    pool: 
      name: self-hosted-agent
    steps:    
    - script: |
        python3.7 -m venv ~/.project2
        source ~/.project2/bin/activate
        pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
        python3.7 venv project2
        source project2/bin/activate
        make install
        make lint
      workingDirectory: $(projectRoot)
      displayName: "Build and lint"
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App : $(webAppName)'
      inputs:
        azureSubscription: $(azureServiceConnectionId)
        appName: $(webAppName)
        package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
